export interface GlossaryEntry { conceptKey: string; noteKey?: string; ctaKey?: string; ctaHref?: string; }
export const TERM_GLOSSARY: Record<string, GlossaryEntry> = {
  fee:           { conceptKey: "help.fee.concept",          noteKey: "help.fee.note", ctaKey: "help.fee.cta", ctaHref: "/learn/fees" },
  savings:       { conceptKey: "help.savings.concept",      noteKey: "help.savings.note" },
  avgGridPrice:  { conceptKey: "help.avg_grid_price.concept" },
  fillPrice:     { conceptKey: "help.fill_price.concept" },
  orderPrice:    { conceptKey: "help.order_price.concept" },
  alpha:         { conceptKey: "help.alpha.concept",        noteKey: "help.alpha.note" },
  makerTaker:    { conceptKey: "help.maker_taker.concept",  noteKey: "help.maker_taker.note" },
  isolation:     { conceptKey: "help.isolation.concept",    noteKey: "help.isolation.note" },
  trailingEntry: { conceptKey: "help.trailing_entry.concept" },
  takeProfit:    { conceptKey: "help.take_profit.concept" },
  mainGrid:      { conceptKey: "help.main_grid.concept" },
  portionSize:   { conceptKey: "help.portion_size.concept" },
  leverage:      { conceptKey: "help.leverage.concept" },
  stopLoss:      { conceptKey: "help.stop_loss.concept",     noteKey: "help.stop_loss.note" },
  activation:    { conceptKey: "help.activation.concept" },
  markPrice:     { conceptKey: "help.mark_price.concept" },
  position:      { conceptKey: "help.position.concept" },
  realizedPnl:   { conceptKey: "help.realized_pnl.concept",  noteKey: "help.realized_pnl.note" },
  unrealizedPnl: { conceptKey: "help.unrealized_pnl.concept" },
  totalPnl:        { conceptKey: "help.total_pnl.concept",       noteKey: "help.total_pnl.note" },
  robotTotalPnl:   { conceptKey: "help.robot_total_pnl.concept" },
  netPnl:          { conceptKey: "help.net_pnl.concept" },
  reorders:      { conceptKey: "help.reorders.concept",      noteKey: "help.reorders.note" },
  // AI 推荐相关术语
  riskTier:          { conceptKey: "help.risk_tier.concept" },
  realizedVolatility:{ conceptKey: "help.realized_volatility.concept" },
  atr:               { conceptKey: "help.atr.concept" },
  maxDrawdown:       { conceptKey: "help.max_drawdown.concept" },
  rangePct:          { conceptKey: "help.range_pct.concept" },
  trend:             { conceptKey: "help.trend.concept" },
  vpvrNode:          { conceptKey: "help.vpvr_node.concept" },
  confidence:        { conceptKey: "help.confidence.concept" },
};
